[package]
name = "aoc"
version = "0.1.0"
authors = ["timhabermaas"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
itertools = "0.10.3"
